# Generated by Django 4.2.5 on 2023-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_user1_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='<django.db.models.fields.related.OneToOneField>', max_length=200),
        ),
    ]
