# Generated by Django 4.2.5 on 2023-09-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='academy_courses/static/profile.jpg', null=True, upload_to=''),
        ),
    ]
