# Generated by Django 4.2.5 on 2023-09-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.JSONField(null=True),
        ),
    ]
