# Generated by Django 4.2.5 on 2023-09-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
