# Generated by Django 4.2.5 on 2023-09-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0004_remove_course_time_course_hours_course_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
