# Generated by Django 4.2.5 on 2023-09-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
