# Generated by Django 4.2.5 on 2023-09-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0008_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Urls', max_length=30)),
                ('icon', models.CharField(choices=[('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-instagram', 'Instagram'), ('fa-linkedin', 'LinkedIn'), ('fa-youtube', 'YouTube'), ('fa-pinterest', 'Pinterest'), ('fa-tumblr', 'Tumblr'), ('fa-flickr', 'Flickr'), ('fa-github', 'GitHub'), ('fa-bitbucket', 'Bitbucket'), ('fa-gitlab', 'GitLab'), ('fa-stack-overflow', 'Stack Overflow'), ('fa-medium', 'Medium'), ('fa-reddit', 'Reddit'), ('fa-whatsapp', 'WhatsApp'), ('fa-skype', 'Skype')], default='Select an icon', max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
