# Generated by Django 4.2.5 on 2023-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0009_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='icon',
            field=models.CharField(choices=[('', 'Select an icon'), ('fa-facebook', 'Facebook'), ('fa-twitter', 'Twitter'), ('fa-instagram', 'Instagram'), ('fa-linkedin', 'LinkedIn'), ('fa-youtube', 'YouTube'), ('fa-pinterest', 'Pinterest'), ('fa-tumblr', 'Tumblr'), ('fa-flickr', 'Flickr'), ('fa-github', 'GitHub'), ('fa-bitbucket', 'Bitbucket'), ('fa-gitlab', 'GitLab'), ('fa-stack-overflow', 'Stack Overflow'), ('fa-medium', 'Medium'), ('fa-reddit', 'Reddit'), ('fa-whatsapp', 'WhatsApp'), ('fa-skype', 'Skype')], default='Select an icon', max_length=100),
        ),
    ]
