# Generated by Django 4.2.5 on 2023-09-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0013_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
