# Generated by Django 4.2.5 on 2023-09-12 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0016_course_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
