# Generated by Django 4.2.5 on 2023-09-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0019_comment_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
    ]
