# Generated by Django 4.2.5 on 2023-09-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0022_order_transaction_orderproduct_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='course',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
