# Generated by Django 4.2.5 on 2023-09-23 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0024_order_transaction_orderproduct_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='session',
        ),
    ]
