# Generated by Django 4.2.5 on 2023-09-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0027_order_transaction_orderproduct_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderProduct',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
