# Generated by Django 4.2.5 on 2023-09-24 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_courses', '0032_alter_transaction_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academy_courses.course'),
        ),
    ]
