# Generated by Django 4.2.5 on 2023-09-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='card_image',
            new_name='cover_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='article',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='article',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sub_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.TextField(max_length=10000),
        ),
    ]
