# Generated by Django 4.2.5 on 2023-09-11 11:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_blog', '0002_rename_card_image_article_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=tinymce.models.HTMLField(max_length=10000),
        ),
    ]
